### ISSUE TITLE
May meeting notes page has link to February meeting video

### ISSUE THREAD

**Issue by mplec** [OpenAssetIO/OpenAssetIO-WG#2]
Looks like the meeting video link on the [2022-05-19 page](https://github.com/OpenAssetIO/OpenAssetIO-WG/tree/main/meetings/2022-05-19) is wrong? I'm getting "GMT20220210-170512_Recording_1570x774.mp4"

**Comment by foundrytom** [comment]
Good spot, thanks! Sorry about that @mplec - sorted now...
